export const ServiceInzu = "250726294387";

export const uiTranslations = {
    fr: {
        subtitle: "Maisons & chambres proches de l'ULK",
        sectionTitle: "Offres disponibles près de l'ULK",
        contactBtn: "Contact",
        prec: "localisation:",
        distance: "Distance ULK:",
        furnished: "Meublé:",
        bathroom: "Toilette / Douche:",
        kitchen: "Cuisine:",
        yes: "Oui",
        no: "Non",
        visitBtn: "Visite Virtuelle sur WhatsApp",
        morePhotosBtn: "Voir plus de photos",
        waMessage: "Hello InzuCampus! I am interested in the listing",
        footerDesc: "Facilite la recherche de logement pour les étudiants internationaux et locaux à Kigali (ULK Gisozi).",
        closeModal: "Fermer",
        loadError: "Impossible de charger les logements. Veuillez réessayer.",
        virtualTours: "Visites virtuelles",
        locationLabel: "Gisozi, Kigali",
        month: "mois"
    },
    en: {
        subtitle: "Houses & rooms near ULK",
        sectionTitle: "Available listings near ULK",
        contactBtn: "Contact",
        prec: "location:",
        distance: "Distance to ULK:",
        furnished: "Furnished:",
        bathroom: "Bathroom:",
        kitchen: "Kitchen:",
        yes: "Yes",
        no: "No",
        visitBtn: "Virtual Tour on WhatsApp",
        morePhotosBtn: "See more photos",
        waMessage: "Hello InzuCampus! I am interested in the listing",
        footerDesc: "Simplifying housing search for international and local students in Kigali (ULK Gisozi).",
        closeModal: "Close",
        loadError: "Unable to load listings. Please try again.",
        virtualTours: "Virtual tours",
        locationLabel: "Gisozi, Kigali",
        month: "month"
    },
    rw: {
        subtitle: "Amazu n'ibyumba hafi ya ULK",
        sectionTitle: "Amazu ahari hafi ya ULK",
        contactBtn: "Twandikire",
        prec: "Ahantu:",
        distance: "Intera kugera kuri ULK:",
        furnished: "Ifite ibikoresho:",
        bathroom: "Ubwiherero:",
        kitchen: "Igikoni:",
        neighborhood: "Agace:",
        yes: "Yego",
        no: "Oya",
        visitBtn: "Sura inzu ukoresheje WhatsApp",
        morePhotosBtn: "Reba andi mafoto",
        waMessage: "Hello InzuCampus! I am interested in the listing",
        footerDesc: "Dufasha abanyeshuri mpuzamahanga n'abo mu Rwanda kubona amacumbi i Kigali (ULK Gisozi).",
        closeModal: "Funga",
        loadError: "Ntibishoboka gufungura amazu. Ongera ugerageze.",
        virtualTours: "Gusura amazu hifashishijwe ikoranabuhanga",
        locationLabel: "Gisozi, Kigali",
        month: "ukwezi"
    },
    ar: {
        subtitle: "منازل وغرف بالقرب من جامعة ULK",
        sectionTitle: "العروض المتاحة بالقرب من جامعة ULK",
        contactBtn: "اتصل بنا",
        prec: "الموقع:",
        distance: "المسافة إلى ULK:",
        furnished: "مفروش:",
        bathroom: "الحمام:",
        kitchen: "المطبخ:",
        neighborhood: "الحي:",
        yes: "نعم",
        no: "لا",
        visitBtn: "جولة افتراضية عبر واتساب",
        morePhotosBtn: "عرض المزيد من الصور",
        waMessage: "Hello InzuCampus! I am interested in the listing",
        footerDesc: "نسهّل البحث عن السكن للطلاب الدوليين والمحليين في كيغالي (ULK غيسوزي).",
        closeModal: "إغلاق",
        loadError: "تعذر تحميل أماكن السكن. يرجى المحاولة مرة أخرى.",
        virtualTours: "جولات افتراضية",
        locationLabel: "غيسوزي، كيغالي",
        month: "شهر"
    }
};
